name: app_environment
channels:
  - snowflake
dependencies:
  - altair=5.0.1
  - lifelines=0.30.0
  - matplotlib=3.10.0
  - networkx=3.4.2
  - plotly=5.24.1
  - python=3.11.*
  - seaborn=0.13.2
  - snowflake-snowpark-python=
  - streamlit=
  - streamlit-echarts=0.4.0
  - streamlit-extras=0.4.0
